apiVersion: v1
kind: Service
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    {{- include "haproxy.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . | quote}}
  {{- end }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.ports }}
  ports:
  {{- range $key, $port := . }}
  - name: {{ $key }}
    protocol: {{ $port.protocol }}
    port: {{ default $port.port $port.containerPort }}
    targetPort: {{ $key }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "haproxy.selectorLabels" . | nindent 4 }}
