apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "netchecker.fullname" . }}-agent
  labels:
    {{- include "netchecker.agentLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "netchecker.agentSelectorLabels" . | nindent 6 }}
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "netchecker.agentSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netchecker.serviceAccountName" . }}-agent
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository.agent }}:{{ .Values.image.tag.agent }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - -v={{ .Values.config.debug }}
            - -alsologtostderr=true
            - -serverendpoint={{ include "netchecker.fullname" . }}-service:{{ .Values.service.port }}
            - -reportinterval={{ .Values.config.reportInterval }}
          resources:
            {{- toYaml .Values.resources.agent | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
