apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "netchecker.serviceAccountName" . }}-server
  labels:
    {{- include "netchecker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "netchecker.serviceAccountName" . }}-server
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "netchecker.serviceAccountName" . }}-server
  apiGroup: rbac.authorization.k8s.io
