apiVersion: v1
kind: Service
metadata:
  name: {{ include "netchecker.fullname" . }}-service
  labels:
    {{- include "netchecker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "netchecker.selectorLabels" . | nindent 4 }}
