apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netchecker.serviceAccountName" . }}-agent
  labels:
    {{- include "netchecker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
